//All constants
package strsd

const (
	MAX_PLAYER_LIFE = 2
	MAX_WALL_LIFE = 10
	GRANADE_FLY_TIME = 5

	WAY_UP = 0
	WAY_RIGHT = 1
	WAY_DOWN = 2
	WAY_LEFT = 3

	ACTION_NONE = 0
	ACTION_MOVE = 1
	ACTION_TURN_RIGHT = 2
	ACTION_TURN_LEFT = 3
	ACTION_SHOOT_BULLET = 4
	ACTION_THROW_GRANADE = 5

	EVENT_TYPE_SHOT = 0
	EVENT_TYPE_EXPLOSION = 1
	EVENT_TYPE_HIT = 2

	DEFAULT_OPTION_FOG_OF_WAR = true
	DEFAULT_OPTION_PERSONAL_SPACE = false
	DEFAULT_OPTION_FIELD_OF_VIEW = true

	DEFAULT_FRAG_LIMIT = 5
)
